CREATE TABLE "storefront_product" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "storefront_product_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"description" text,
	"price" integer NOT NULL,
	"currencyCode" varchar(3) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
DROP TABLE "storefront_post" CASCADE;--> statement-breakpoint
CREATE INDEX "product_name_idx" ON "storefront_product" USING btree ("name");